version: '3'

volumes:
  data:

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=banco
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"